import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Element</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <section className={styles.hero}>

         <div className={styles.hero__image}>
           <Image 
           className={styles.image}
            // src='https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80'
            src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80"
            alt='admin world'
            layout='fill'
            objectFit='cover'
            objectPosition='center'
            // width={2250}
            // height={1390}           
            // layout='responsive'
           />           
         </div>

         <div className={`${styles['container']} ${styles['hero__container']}`}>
            <div className={styles.herowrapper}>
               <h1 className={styles.herowrapper__heading}>Every business has an <span>Admin Element</span>.</h1>
               <p className={styles.herowrapper__body}>
                  Let us focus on your admin so you don't have to.
               </p>
           </div>
         </div>
       </section>

       <section className={styles.pt1}> {/* <section className={`${styles['categories']} ${styles['pt1']}`}> */}
			  <h1 className={styles.sr_only}>Zoo365</h1>

			  <div className={`${styles['container']} ${styles['training']}`}>

				<div className={`${styles['training__card']} ${styles['training__card_square']}`}>
					<h3 className={styles.training__card_title}>General</h3>
					<div className={styles.image_overlay}></div>
					<div className={styles.training__image}>
						<Image
            // src="https://images.unsplash.com/photo-1568667256549-094345857637?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGxpYnJhcnl8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"
             src="https://images.unsplash.com/photo-1562240020-ce31ccb0fa7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmlsbHN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60" 
             alt="admin world" 
             layout='fill'
             objectFit='cover'
             />                        
					</div>
				</div>

				<div className={`${styles['training__card']} ${styles['training__card_square']}`}>
					<h3 className={styles.training__card_title}>Business</h3>
					<div className={styles.image_overlay}></div>
					<div className={styles.training__image}>
						<Image
             src="https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YnVzaW5lc3MlMjBhZG1pbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" 
             alt="admin world" 
             layout='fill'
             objectFit='cover'
             />                        
					</div>
				</div>

        <div className={`${styles['training__card']} ${styles['training__card_square']}`}>
					<h3 className={styles.training__card_title}>Personal</h3>
					<div className={styles.image_overlay}></div>
					<div className={styles.training__image}>
						<Image
             src="https://images.unsplash.com/photo-1556020685-ae41abfc9365?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8YmVkcm9vbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" 
            //  src="https://images.unsplash.com/photo-1483058712412-4245e9b90334?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHBlcnNvbmFsJTIwbGlmZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60"
             alt="admin world" 
             layout='fill'
             objectFit='cover'
             />                        
					</div>
				</div>        
        </div>
		   </section>
      
       <section className={`${styles['getstarted']} ${styles['mt1']}`}>
		  	<div className={styles.overlay}>
        <Image
          src="https://images.unsplash.com/photo-1599689444589-133726281155?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d2h5JTIwd2FpdHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" 
          alt="admin world" 
         layout='fill'
         z-index= '-1'
         objectFit='cover'
         />                  
        </div>

		  	<div className={styles.container}>
				<h1 className={styles.textcenter}>Get Started Today<br/> <span>Why Wait?</span></h1>
				{/* <a href="#" class="button button--primary">Sign up</a> */}
			  </div>
		  </section>

      <section className={`${styles['trainingoptions']} ${styles['pt1']}`}>

			  <div className={styles.container}>
 
			  	<h1  className={`${styles['trainingoption__headings']} ${styles['textcenter']}`}>Your Package <span>Options</span></h1>
			  	<p  className={`${styles['trainingoptions__body']} ${styles['textcenter']}`}>Whether for a one off job, small or large project or short or long term. We have got you covered<br/> Choose from one of our 3 packages that best suits you needs <br/>Terms and conditions may apply.</p>
     

		  	<div className={`${styles['training']} ${styles['trainingoptions']} ${styles['pt1']}`}>
				
         <div className={styles.training__card}>
					  <h3 className={styles.training__card_title}>Bronze</h3>
           <p className={styles.training__card_body}>40 per hour</p>
					  <div className={styles.image_overlay}></div>
				  	<div className={styles.training__image}>
						  <Image
               src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" 
               alt="admin world" 
               layout='fill'
               objectFit='cover'
               objectPosition='center'
               />                        
					  </div>
				  </div>

          <div className={styles.training__card}>
				  	<h3 className={styles.training__card_title}>Silver</h3>
           <p className={styles.training__card_body}>800 per month</p>
				  	<div className={styles.image_overlay}></div>
				  	<div className={styles.training__image}>
					  	<Image
               src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" 
               alt="admin world" 
              layout='fill'
              objectFit='cover'
               />                        
				  	</div>
			  	</div>

         <div className={styles.training__card}>
				  	<h3 className={styles.training__card_title}>Gold</h3>
            <p className={styles.training__card_body}> 2000 per month</p>
					  <div className={styles.image_overlay}></div>
				  	<div className={styles.training__image}>
						  <Image
               src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" 
              alt="admin world" 
              layout='fill'
              objectFit='cover'
               />                        
				  	</div>
				  </div>				
			</div>
			</div>
		</section>
		
    <section className={`${styles['getstarted']} ${styles['mt1']}`}>
		  	<div className={styles.overlay}>
          <Image
            src="https://images.unsplash.com/photo-1504297050568-910d24c426d3?ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=334&q=80" 
           alt="admin world" 
           layout='fill'
           z-index= '-1'
           objectFit='cover'
           />                  
        </div>

		  	<div className={styles.container}>
			  	<h1 className={styles.textcenter}>WE WILL HELP YOU GET
          YOUR ADMIN IN SHAPE<br/>
          <span>LET'S GET STARTED</span></h1>
			  	{/* <a href="#" class="button button--primary">Sign up</a> */}
			  </div>
		</section>

    <footer className={`${styles['footer']} ${styles['pt1']}`}>

		<div className={`${styles['container']} ${styles['footercontainer']}`}>
			<div className={styles.footercol}>
				<h3 className={styles.footercol__heading}>Find Us</h3>
				<ul className={styles.footercol__list}>
					<li className={styles.li}>Address: 43 House Wandsworth London SW18 2BB</li>
					<li className={styles.li}>Contact: 0208 785 2233</li>
          <li className={styles.li}>Email: info@adminelement.com</li>
				</ul>
			</div>

			{/* <div className={styles.footer-col}>
				<h3 className={styles.footer-col__heading}>Get Assistance</h3>
				<ul className={styles.footer-col__list}>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
				</ul>
			</div>

			<div class="footer-col">
				<h3 class="footer-col__heading">Company</h3>
				<ul class="footer-col__list">
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
				</ul>
			</div>

			<div class="footer-col">
				<h3 class="footer-col__heading">Keep In Touch</h3>
				<ul class="footer-col__list">
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
					<li><a href="#">Link</a></li>
				</ul>
			</div> */}

		</div>
    
		<div className={`${styles['container']} ${styles['textcenter']} ${styles['footer__copyright']}`}>
			<p className={styles.pt1}>&copy; 2021 Admin Element - Created by Web Design</p>
		</div>

	</footer>

  </main>      
</div>
  )
}
